/// @file       /src/dsf/headers/FirstOrderDynamics.hpp
/// @brief      Defines the FirstOrderDynamics class.
///
/// @details    This file contains the definition of the FirstOrderDynamics class.
///             The FirstOrderDynamics class represents the dynamics of the network. It is templated by the type
///             of the graph's id and the type of the graph's capacity.
///             The graph's id and capacity must be unsigned integral types.

#pragma once

#include <algorithm>
#include <atomic>
#include <cassert>
#include <cmath>
#include <concepts>
#include <exception>
#include <format>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <optional>
#include <random>
#include <span>
#include <sstream>
#include <iostream>
#include <thread>
#include <tuple>
#include <unordered_map>
#include <variant>
#include <vector>

#include <tbb/tbb.h>
#include <spdlog/spdlog.h>

#include "../base/Dynamics.hpp"
#include "Agent.hpp"
#include "Itinerary.hpp"
#include "RoadNetwork.hpp"
#include "../utility/Typedef.hpp"

static constexpr auto CACHE_FOLDER = "./.dsfcache/";

namespace dsf::mobility {
  using TurnCountsDict =
      tbb::concurrent_unordered_map<Id, tbb::concurrent_unordered_map<Id, std::size_t>>;
  /// @brief The method for inserting agents into the network
  enum class AgentInsertionMethod : std::uint8_t {
    RANDOM = 0,  // Agents spawn randomly in the network and travel with no destination
    RANDOM_WEIGHTED_ORIGIN =
        1,  // Agents are generated by randomly selecting their origin according to the weights
    ODS = 2,  // Agents are generated according to the provided OD pairs
    RANDOM_ODS =
        3,  // Agents are generated by randomly selecting their origin and destination according to the weights
    UNIFORM = 4,  // Agents spawn uniformly directly onto available edges (streets)
    CONDITIONAL_RANDOM_ODS =
        5,  // Agents are generated by randomly selecting their origin according to the weights, then randomly selecting their destination according to the conditional weights
  };
  // Struct to collect street data for batch insert after parallel section
  struct StreetDataRecord {
    std::optional<std::string> coilName;
    double density;
    std::optional<double> avgSpeed;
    std::optional<double> stdSpeed;
    std::optional<std::size_t> nObservations;
    std::optional<std::size_t> counts;
    std::size_t queueLength;
  };
  struct AverageStatsRecord {
    std::size_t nValidEdges{0};
    double meanSpeed{0.};
    double stdSpeed{0.};
    double meanDensity{0.};
    double stdDensity{0.};
    double meanTravelTime{0.};
    double meanQueueLength{0.};
  };
  struct StepDataRequest {
    bool saveAverageStats{false};
    bool saveStreetData{false};
    bool saveTravelData{false};
    bool saveAgentData{false};
    bool saveTurnCounts{false};
  };
  struct StepDataResult {
    std::time_t timeStep{0};
    std::optional<tbb::concurrent_map<Id, StreetDataRecord>> streetData;
    std::optional<tbb::concurrent_vector<std::pair<double, double>>> travelData;
    std::optional<AverageStatsRecord> averageStats;
    std::optional<tbb::concurrent_unordered_map<
        Id,
        std::vector<std::tuple<Id, std::time_t, std::time_t>>>>
        agentData;
    TurnCountsDict turnCounts;
  };
  /// @brief The FirstOrderDynamics class represents the dynamics of the network.
  class FirstOrderDynamics : public Dynamics<RoadNetwork> {
    std::vector<Id> m_nodeIndices;
    std::vector<std::unique_ptr<Agent>> m_agents;
    std::unordered_map<Id, std::shared_ptr<Itinerary>> m_itineraries;
    std::vector<std::tuple<Id, double>> m_origins;
    std::vector<std::tuple<Id, double>> m_destinations;
    std::vector<std::tuple<Id, Id, double>> m_ODs;
    std::vector<double> m_ODCumulativeWeights;
    // Conditional Origin -> Destinations
    std::unordered_map<Id, std::vector<std::tuple<Id, double>>> m_originToDestinations;
    // ---
    tbb::concurrent_unordered_map<Id, std::size_t> m_originCounts;
    tbb::concurrent_unordered_map<Id, std::size_t> m_destinationCounts;
    std::atomic<std::size_t> m_nAgents{0}, m_nAddedAgents{0}, m_nInsertedAgents{0},
        m_nKilledAgents{0}, m_nArrivedAgents{0};
    std::function<double(Street const&)> m_speedFunction;
    std::string m_speedFunctionDescription;
    double m_uturnPenaltyFactor = 0.1;
    bool m_updatepathsThrowOnEmpty = true;
    bool m_reinsertAgents = false;

  protected:
    TurnCountsDict m_turnCounts;
    tbb::concurrent_unordered_map<Id, std::unordered_map<Direction, double>>
        m_queuesAtTrafficLights;
    tbb::concurrent_vector<std::pair<double, double>> m_travelDTs;
    std::time_t m_previousOptimizationTime{0};

  protected:
    std::optional<double> m_errorProbability{std::nullopt};
    std::optional<double> m_passageProbability{std::nullopt};
    std::optional<double> m_meanTravelDistance{std::nullopt};
    std::optional<std::time_t> m_meanTravelTime{std::nullopt};
    std::optional<Delay> m_dataUpdatePeriod;
    bool m_bCacheEnabled;
    std::optional<double> m_timeToleranceFactor{std::nullopt};
    bool m_forcePriorities{false};

  private:
    /// @brief Kill an agent from the dynamics
    /// @tparam Arrived A boolean indicating whether the agent has arrived at its destination
    /// @param pAgent A std::unique_ptr to the agent to kill
    template <bool Arrived>
    std::unique_ptr<Agent> m_removeAgent(std::unique_ptr<Agent> pAgent);
    /// @brief Update the path of a single itinerary using Dijsktra's algorithm
    /// @param pItinerary An std::shared_ptr to the itinerary
    void m_updatePath(std::shared_ptr<Itinerary> const& pItinerary);

    template <bool Uniformly>
    void m_addAgentsRandom(std::size_t nAgents);
    void m_addAgentsODs(std::size_t nAgents);
    void m_addAgentsRandomODs(std::size_t nAgents);
    void m_addAgentsConditionalRandomODs(std::size_t nAgents);

    std::optional<Id> m_extractStreet(
        std::unordered_map<Id, double> const& transitionProbabilities,
        double const cumulativeProbability);

    std::optional<Id> m_nextRandomStreetId(const std::unique_ptr<Agent>& pAgent,
                                           RoadJunction const* pNode);
    /// @brief Get the next street id
    /// @param pAgent A std::unique_ptr to the agent
    /// @param pNode A std::unique_ptr to the current node
    /// @return Id The id of the randomly selected next street
    std::optional<Id> m_nextStreetId(const std::unique_ptr<Agent>& pAgent,
                                     RoadJunction const* pNode);
    /// @brief Evolve a street
    /// @param pStreet A std::unique_ptr to the street
    /// @details If possible, removes the first agent of the street's queue, putting it in the destination node.
    void m_evolveStreet(Street* pStreet);
    /// @brief If possible, removes one agent from the node, putting it on the next street.
    /// @param pNode A std::unique_ptr to the node
    void m_evolveNode(RoadJunction* pNode);
    /// @brief Evolve the agents.
    /// @details Puts all new agents on a street, if possible, decrements all delays
    /// and increments all travel times.
    void m_evolveAgents();

    void m_trafficlightSingleTailOptimizer(double const beta,
                                           std::optional<std::ofstream>& logStream);

    void m_importNodeODsFromCSV(std::string_view const fileName,
                                char const separator = ';');

    void m_importEdgeODsFromCSV(std::string_view const fileName,
                                char const separator = ';');

  public:
    /// @brief Construct a new FirstOrderDynamics object
    /// @param graph The graph representing the network
    /// @param useCache If true, the cache is used (default is false)
    /// @param seed The seed for the random number generator (default is std::nullopt)
    FirstOrderDynamics(RoadNetwork&& graph,
                       bool useCache = false,
                       std::optional<unsigned int> seed = std::nullopt);

    /// @brief Automatically prepare the network for the simulation. This method calls the following methods in order:
    /// - RoadNetwork::adjustNodeCapacities()
    /// - RoadNetwork::autoMapStreetLanes()
    /// - RoadNetwork::autoAssignRoadPriorities()
    /// - RoadNetwork::autoInitTrafficLights()
    /// @param bAdjustNodeCapacities If true, the nodes' capacities are adjusted using the streets' transport capacities (default is true)
    /// @param bAutoMapStreetLanes If true, the streets' lanes are automatically mapped using the network's topology (default is false)
    /// @param bAutoAssignRoadPriorities If true, the streets' priorities are automatically assigned using the network's topology (default is true)
    /// @param bAutoInitTrafficLights If true, the traffic lights' phases are automatically initialized using the streets' geometry (default is true)
    void prepareNetwork(bool const bAdjustNodeCapacities = true,
                        bool const bAutoMapStreetLanes = false,
                        bool const bAutoAssignRoadPriorities = true,
                        bool const bAutoInitTrafficLights = true);
    /// @brief Set the error probability
    /// @param errorProbability The error probability
    /// @throw std::invalid_argument If the error probability is not between 0 and 1
    void setErrorProbability(double errorProbability);
    /// @brief Set the passage probability
    /// @param passageProbability The passage probability
    /// @details The passage probability is the probability of passing through a node
    ///   It is useful in the case of random agents
    void setPassageProbability(double passageProbability);
    /// @brief Set the time tolerance factor for killing stagnant agents.
    ///   An agent will be considered stagnant if it has not moved for timeToleranceFactor * std::ceil(street_length / street_maxSpeed) time units.
    /// @param timeToleranceFactor The time tolerance factor
    /// @throw std::invalid_argument If the time tolerance factor is not positive
    void killStagnantAgents(double timeToleranceFactor = 3.);
    /// @brief Enable data saving (compatibility wrapper; persistence is handled by TrafficSimulator).
    void saveData(std::time_t const savingInterval,
                  bool const saveAverageStats = false,
                  bool const saveStreetData = false,
                  bool const saveTravelData = false,
                  bool const saveAgentData = false);
    /// @brief Set the speed function. Options are:
    /// - (LINEAR, alpha): speed = max_speed * (1 - alpha * density), where alpha is a parameter in [0, 1)
    /// - (CUSTOM, func): speed = func(pointer to a street), where func is a callable provided by the user that takes the street's pointer.
    template <typename... TArgs>
    void setSpeedFunction(SpeedFunction const speedFunction, TArgs&&... args);
    /// @brief Set the force priorities flag
    /// @param forcePriorities The flag
    /// @details If true, if an agent cannot move to the next street, the whole node is skipped
    inline void setForcePriorities(bool const forcePriorities) noexcept {
      m_forcePriorities = forcePriorities;
    }
    /// @brief Set the update paths throw on empty flag
    /// @param throwOnEmpty The flag
    /// @details If true, if an itinerary has an empty path when updating paths, an exception is thrown. If false, the itinerary is left unchanged.
    inline void setUpdatePathsThrowOnEmpty(bool const throwOnEmpty) noexcept {
      m_updatepathsThrowOnEmpty = throwOnEmpty;
    }
    /// @brief Set the data update period.
    /// @param dataUpdatePeriod Delay, The period
    /// @details Some data, i.e. the street queue lengths, are stored only after a fixed amount of time which is represented by this variable.
    inline void setDataUpdatePeriod(Delay const dataUpdatePeriod) noexcept {
      m_dataUpdatePeriod = dataUpdatePeriod;
    }
    /// @brief Set the mean distance travelled by a random agent. The distance will be sampled from an exponential distribution with this mean.
    /// @param meanTravelDistance The mean distance
    /// @throw std::invalid_argument If the mean distance is negative
    inline void setMeanTravelDistance(double const meanTravelDistance) {
      meanTravelDistance > 0. ? m_meanTravelDistance = meanTravelDistance
                              : throw std::invalid_argument(
                                    "FirstOrderDynamics::setMeanTravelDistance: "
                                    "meanTravelDistance must be positive");
    };
    /// @brief Set the mean travel time for random agents. The travel time will be sampled from an exponential distribution with this mean.
    /// @param meanTravelTime The mean travel time
    inline void setMeanTravelTime(std::time_t const meanTravelTime) noexcept {
      m_meanTravelTime = meanTravelTime;
    };
    /// @brief Set the penalty factor applied to U-turns when choosing the next street.
    /// @param uturnPenaltyFactor The penalty factor, which must be positive.
    /// @throw std::invalid_argument If the penalty factor is not positive.
    inline void setUTurnPenaltyFactor(double uturnPenaltyFactor) {
      if (uturnPenaltyFactor <= 0.) {
        throw std::invalid_argument(std::format(
            "The U-turn penalty factor ({}) must be positive", uturnPenaltyFactor));
      }
      m_uturnPenaltyFactor = uturnPenaltyFactor;
    }
    inline void setReinsertAgents(bool const reinsertAgents) noexcept {
      m_reinsertAgents = reinsertAgents;
    }
    /// @brief Set the origins
    /// @param origins The origin nodes
    void setOrigins(std::unordered_map<Id, double> const& origins = {});
    /// @brief Set the destinations
    /// @param destinations The destinations
    void setDestinations(std::unordered_map<Id, double> const& destinations);
    /// @brief Set the destinations
    /// @param destinations The destinations (as an initializer list)
    void setDestinations(std::initializer_list<Id> destinations);
    /// @brief Set the origin-destination pairs with their associated weights
    /// @param ODs A vector of tuples (origin node id, destination node id, weight)
    void setODs(std::vector<std::tuple<Id, Id, double>> const& ODs);
    /// @brief Set the origin-destination pairs with their associated weights from a map of origin nodes to vectors of destination nodes and weights.
    /// @param originToDestinations An unordered map where the keys are origin node ids and the values are origin weights and vectors of tuples (destination node id, weight)
    void setConditionalODs(
        std::unordered_map<Id,
                           std::tuple<double, std::vector<std::tuple<Id, double>>>> const&
            originToDestinations);
    /// @brief Set the destinations
    /// @param destinations A container of destination ids
    /// @details The container must have a value_type convertible to Id and begin() and end() methods
    template <typename TContainer>
      requires(std::is_convertible_v<typename TContainer::value_type, Id>)
    void setDestinations(TContainer const& destinationNodes);
    /// @brief Import origin-destination pairs from a CSV file. Possibilities are:
    /// - origin_id;destination_id;weight (for AgentInsertionMethod::ODS)
    /// - node_id;type;weight (for AgentInsertionMethod::RANDOM_ODS, where type is either "O" or "D")
    /// - origin_id;weight;destinations (for AgentInsertionMethod::CONDITIONAL_RANDOM_ODS, where destinations is a comma-separated list of destination_id:weight pairs)
    void importODsFromCSV(std::string_view const fileName,
                          char const separator = ';',
                          bool const bEdges = true);

    /// @brief Initialize the turn counts map
    /// @throws std::runtime_error if the turn counts map is already initialized
    void initTurnCounts();
    /// @brief Reset the turn counts map values to zero
    /// @throws std::runtime_error if the turn counts map is not initialized
    void resetTurnCounts();
    /// @brief Update the paths of the itineraries based on the given weight function
    /// @throws std::runtime_error if m_updatepathsThrowOnEmpty is true and an itinerary has an empty path
    void updatePaths();
    /// @brief Add agents uniformly on the road network
    /// @param nAgents The number of agents to add
    /// @param itineraryId The id of the itinerary to use (default is std::nullopt)
    /// @throw std::runtime_error If there are no itineraries
    void addAgentsUniformly(std::size_t nAgents,
                            std::optional<Id> itineraryId = std::nullopt);

    /// @brief Add an agent to the simulation
    /// @param agent std::unique_ptr to the agent
    void addAgent(std::unique_ptr<Agent> agent);
    /// @brief Add an agent to the simulation
    /// @param trip std::vector of std::shared_ptr to the itineraries
    /// @param optSrcStreetId std::optional<Id> representing the source street id. If not provided, the source street will be selected randomly.
    void addAgent(std::vector<std::shared_ptr<Itinerary>> const& trip,
                  std::optional<Id> optSrcStreetId = std::nullopt);
    /// @brief Add an agent to the simulation
    /// @param pItinerary std::shared_ptr to the itinerary
    /// @details If pItinerary is nullptr, the agent will be added without an itinerary
    /// @param optSrcStreetId std::optional<Id> representing the source street id. If not provided, the source street will be selected randomly.
    void addAgent(std::shared_ptr<Itinerary> pItinerary = nullptr,
                  std::optional<Id> optSrcStreetId = std::nullopt);

    /// @brief Add agents to the simulation
    /// @param nAgents The number of agents to add
    /// @param mode The method to use for adding the agents.Possible values are:
    /// - ODS: Agents are generated according to the provided OD pairs
    /// - RANDOM: Agents spwan randomly in the network and travel with no destination
    /// - RANDOM_ODS: Agents are generated by randomly selecting their origin and destination according to the weights
    void addAgents(std::size_t const nAgents, AgentInsertionMethod const mode);

    /// @brief Add an itinerary
    /// @param ...args The arguments to construct the itinerary
    /// @details The arguments must be compatible with any constructor of the Itinerary class
    template <typename... TArgs>
      requires(std::is_constructible_v<Itinerary, TArgs...>)
    void addItinerary(TArgs&&... args);
    /// @brief Add an itinerary
    /// @param itinerary std::unique_ptr to the itinerary
    /// @throws std::invalid_argument If the itinerary already exists
    /// @throws std::invalid_argument If the itinerary's destination is not a node of the graph
    void addItinerary(std::shared_ptr<Itinerary> itinerary);

    /// @brief Evolve the simulation
    /// @details Evolve the simulation by moving the agents and updating the travel times.
    /// In particular:
    /// - Move the first agent of each street queue, if possible, putting it in the next node
    /// - Move the agents from each node, if possible, putting them in the next street and giving them a speed.
    /// If the error probability is not zero, the agents can move to a random street.
    /// If the agent is in the destination node, it is removed from the simulation (and then reinserted if reinsert_agents is true)
    /// - Cycle over agents and update their times
    /// @param dataRequest The save/collection request for the current step
    /// @return StepDataResult The collected data for the current step
    StepDataResult evolve(StepDataRequest const& dataRequest = {});
    /// @brief Optimize the traffic lights by changing the green and red times
    /// @param optimizationType TrafficLightOptimization, The type of optimization. Default is DOUBLE_TAIL
    /// @param logFile The file into which write the logs (default is empty, meaning no logging)
    /// @param percentage double, the maximum amount (percentage) of the green time to change (default is 0.3)
    /// @param threshold double, The ratio between the self-density and neighbour density to trigger the non-local optimization (default is 1.3)
    /// @details The local optimization is done by changing the green time of each traffic light, trying to make it proportional to the
    ///    queue lengths at each phase. The non-local optimization is done by synchronizing the traffic lights which are congested over threshold.
    void optimizeTrafficLights(
        TrafficLightOptimization optimizationType = TrafficLightOptimization::DOUBLE_TAIL,
        const std::string& logFile = std::string(),
        double const percentage = 0.3,
        double const threshold = 1.3);

    /// @brief Get the itineraries
    /// @return const std::unordered_map<Id, Itinerary>&, The itineraries
    inline auto const& itineraries() const noexcept { return m_itineraries; }
    /// @brief Get the origin nodes of the graph
    /// @return std::vector<std::tuple<Id, double>> const& The origin nodes of the graph
    inline auto const& origins() const noexcept { return m_origins; }
    /// @brief Get the origin nodes of the graph
    /// @return std::vector<std::tuple<Id, double>>& The origin nodes of the graph
    inline auto& origins() noexcept { return m_origins; }
    /// @brief Get the destination nodes of the graph
    /// @return std::vector<std::tuple<Id, double>> const& The destination nodes of the graph
    inline auto const& destinations() const noexcept { return m_destinations; }
    /// @brief Get the destination nodes of the graph
    /// @return std::vector<std::tuple<Id, double>>>& The destination nodes of the graph
    inline auto& destinations() noexcept { return m_destinations; }
    /// @brief Get the agents
    /// @return const std::unordered_map<Id, Agent<Id>>&, The agents
    inline const std::vector<std::unique_ptr<Agent>>& agents() const noexcept {
      return m_agents;
    }
    /// @brief Get the number of agents currently in the simulation
    /// @return std::size_t The number of agents
    inline auto nAgents() const { return m_nAgents.load(); };
    /// @brief Get the number of ghost agents waiting to be inserted
    /// @return std::size_t The number of ghost agents
    inline auto ghostAgents() const { return m_agents.size(); }

    /// @brief Get the mean travel time of the agents in \f$s\f$
    /// @param clearData If true, the travel times are cleared after the computation
    /// @return Measurement<double> The mean travel time of the agents and the standard deviation
    Measurement<double> meanTravelTime(bool clearData = false);
    /// @brief Get the mean travel distance of the agents in \f$m\f$
    /// @param clearData If true, the travel distances are cleared after the computation
    /// @return Measurement<double> The mean travel distance of the agents and the standard deviation
    Measurement<double> meanTravelDistance(bool clearData = false);
    /// @brief Get the mean travel speed of the agents in \f$m/s\f$
    /// @param clearData If true, the travel times and distances are cleared after the computation
    /// @return Measurement<double> The mean travel speed of the agents and the standard deviation
    Measurement<double> meanTravelSpeed(bool clearData = false);
    /// @brief Get the turn counts of the agents
    /// @return const std::unordered_map<Id, std::unordered_map<Id, size_t>>& The turn counts. The outer map's key is the street id, the inner map's key is the next street id and the value is the number of counts
    inline TurnCountsDict const& turnCounts() const noexcept { return m_turnCounts; };
    /// @brief Get the normalized turn counts of the agents
    /// @return const std::unordered_map<Id, std::unordered_map<Id, double>>& The normalized turn counts. The outer map's key is the street id, the inner map's key is the next street id and the value is the normalized number of counts
    std::unordered_map<Id, std::unordered_map<Id, double>> const normalizedTurnCounts()
        const noexcept;

    /// @brief Get the origin counts of the agents
    /// @param bReset If true, the origin counts are cleared (default is true)
    tbb::concurrent_unordered_map<Id, std::size_t> originCounts(
        bool const bReset = true) noexcept;
    /// @brief Get the destination counts of the agents
    /// @param bReset If true, the destination counts are cleared (default is true)
    tbb::concurrent_unordered_map<Id, std::size_t> destinationCounts(
        bool const bReset = true) noexcept;

    /// @brief Get the mean density of the streets in \f$m^{-1}\f$ or \f$a.u.\f$ if Normalized
    /// @tparam Normalized If true, the density is normalized by the street's capacity
    /// @return Measurement<double> The mean density of the streets and the standard deviation
    template <bool Normalized>
    Measurement<double> streetMeanDensity() const;
    /// @brief Get the mean flow of the streets in \f$s^{-1}\f$
    /// @return Measurement<double> The mean flow of the streets and the standard deviation
    Measurement<double> streetMeanFlow() const;
    /// @brief Get the mean flow of the streets in \f$s^{-1}\f$
    /// @param threshold The density threshold to consider
    /// @param above If true, the function returns the mean flow of the streets with a density above the threshold, otherwise below
    /// @return Measurement<double> The mean flow of the streets and the standard deviation
    Measurement<double> streetMeanFlow(double threshold, bool above) const;

    /// @brief Get agents stats from this Dynamics as the following tuple: (nAddedAgents, nInsertedAgents, nArrivedAgents, nKilledAgents, nAgents)
    /// @return std::tuple<std::size_t, std::size_t, std::size_t, std::size_t, std::size_t> The tuple containing the agents stats
    inline auto agentStats() const noexcept {
      return std::make_tuple(m_nAddedAgents.load(),
                             m_nInsertedAgents.load(),
                             m_nArrivedAgents.load(),
                             m_nKilledAgents.load(),
                             m_nAgents.load());
    }
    /// @brief Print a summary of the dynamics to an output stream
    /// @param os The output stream to write to (default is std::cout)
    /// @details The summary includes:
    /// - The RoadNetwork description (nodes, edges, capacity, intersections, traffic lights, roundabouts, coil sensors)
    /// - Number of inserted agents
    /// - Number of added agents
    /// - Number of arrived agents
    /// - Number of killed agents
    /// - Current number of agents in the simulation
    void summary(std::ostream& os = std::cout) const;
  };

  template <bool Arrived>
  inline std::unique_ptr<Agent> FirstOrderDynamics::m_removeAgent(
      std::unique_ptr<Agent> pAgent) {
    --m_nAgents;
    if constexpr (Arrived) {
      spdlog::trace("Removing agent {}", *pAgent);
      ++m_nArrivedAgents;
    } else {
      spdlog::trace("Killing agent {}", *pAgent);
      ++m_nKilledAgents;
    }
    m_travelDTs.push_back({pAgent->distance(),
                           static_cast<double>(this->time_step() - pAgent->spawnTime())});

    auto const optNextStreetId = pAgent->nextStreetId();
    if (optNextStreetId.has_value()) {
      spdlog::trace("Incrementing destination count for street {}", *optNextStreetId);
      auto [it, bInserted] = m_destinationCounts.insert({*optNextStreetId, 1});
      if (!bInserted) {
        ++it->second;
      }
    }
    return pAgent;
  }

  template <typename... TArgs>
  void FirstOrderDynamics::setSpeedFunction(SpeedFunction const speedFunction,
                                            TArgs&&... args) {
    switch (speedFunction) {
      case SpeedFunction::CUSTOM:
        // Assert that the only argument is a function with the correct signature
        if constexpr (sizeof...(args) != 1) {
          throw std::invalid_argument(std::format(
              "Custom speed function requires exactly one argument, but {} were provided",
              sizeof...(args)));
        } else if constexpr (!std::is_invocable_r_v<
                                 double,
                                 std::tuple_element_t<0, std::tuple<TArgs...>>,
                                 Street const&>) {
          throw std::invalid_argument(
              "Custom speed function requires a callable argument with signature "
              "double(Street const&)");
        } else {
          auto const customSpeedFunction = std::function<double(Street const&)>(
              std::get<0>(std::forward_as_tuple(args...)));
          m_speedFunction = customSpeedFunction;
          Street::setEstimatedTravelTimeFunction(
              [customSpeedFunction](Street const& pStreet) {
                return pStreet.length() / customSpeedFunction(pStreet);
              });
          m_speedFunctionDescription = "CUSTOM";
        }
        break;
      case SpeedFunction::LINEAR:
        // There should be only one argument, named "alpha", so check it and extract it
        if constexpr (sizeof...(args) != 1) {
          throw std::invalid_argument(std::format(
              "Linear speed function requires exactly one argument, but {} were provided",
              sizeof...(args)));
        } else if constexpr (!std::is_convertible_v<
                                 std::tuple_element_t<0, std::tuple<TArgs...>>,
                                 double>) {
          throw std::invalid_argument(std::format(
              "Linear speed function requires a double argument, but {} was provided",
              typeid(std::remove_cvref_t<std::tuple_element_t<0, std::tuple<TArgs...>>>)
                  .name()));
        } else {
          double alpha = std::get<0>(std::forward_as_tuple(args...));
          if (alpha < 0. || alpha >= 1.) {
            throw std::invalid_argument(
                std::format("The alpha parameter ({}) must be in [0., 1)", alpha));
          }
          m_speedFunction = [alpha](Street const& pStreet) {
            return pStreet.maxSpeed() * (1. - alpha * pStreet.density<true>());
          };
          Street::setEstimatedTravelTimeFunction([alpha](Street const& pStreet) {
            return pStreet.length() /
                   (pStreet.maxSpeed() * (1. - alpha * pStreet.density<true>()));
          });
          m_speedFunctionDescription = std::format("LINEAR(alpha={})", alpha);
        }
        break;
    }
  }

  template <bool Uniformly>
  inline void FirstOrderDynamics::m_addAgentsRandom(std::size_t nAgents) {
    m_nAddedAgents += nAgents;
    std::exponential_distribution<double> distDist{1. /
                                                   m_meanTravelDistance.value_or(1.)};
    std::exponential_distribution<double> timeDist{1. / m_meanTravelTime.value_or(1.)};
    if constexpr (Uniformly) {
      while (nAgents--) {
        this->addAgent();
        if (m_meanTravelDistance.has_value()) {
          this->m_agents.back()->setMaxDistance(distDist(this->m_generator));
        }
        if (m_meanTravelTime.has_value()) {
          this->m_agents.back()->setMaxTime(timeDist(this->m_generator));
        }
      }
    } else {
      std::uniform_real_distribution<double> uniformDist{0., 1.};
      if (m_origins.empty()) {
        throw std::runtime_error(
            "FirstOrderDynamics::m_addAgentsRandom: No origin nodes set");
      }
      while (nAgents--) {
        auto randValue{uniformDist(this->m_generator)};
        for (auto const& [origin, weight] : m_origins) {
          if (randValue < weight) {
            this->addAgent(nullptr, origin);
            break;
          }
          randValue -= weight;
        }
        if (m_meanTravelDistance.has_value()) {
          this->m_agents.back()->setMaxDistance(distDist(this->m_generator));
        }
        if (m_meanTravelTime.has_value()) {
          this->m_agents.back()->setMaxTime(timeDist(this->m_generator));
        }
      }
    }
  }

  template <typename TContainer>
    requires(std::is_convertible_v<typename TContainer::value_type, Id>)
  void FirstOrderDynamics::setDestinations(TContainer const& destinations) {
    m_itineraries.clear();
    auto const N{destinations.size()};
    m_destinations.clear();
    m_destinations.reserve(N);
    double const UNIFORM_WEIGHT{1. / N};
    std::for_each(destinations.begin(),
                  destinations.end(),
                  [this, UNIFORM_WEIGHT](auto const& id) -> void {
                    this->m_destinations.push_back({id, UNIFORM_WEIGHT});
                    this->addItinerary(id, id);
                  });
  }

  template <typename... TArgs>
    requires(std::is_constructible_v<Itinerary, TArgs...>)
  void FirstOrderDynamics::addItinerary(TArgs&&... args) {
    addItinerary(std::make_shared<Itinerary>(std::forward<TArgs>(args)...));
  }

  template <bool Normalized>
  inline Measurement<double> FirstOrderDynamics::streetMeanDensity() const {
    if (this->graph().edges().empty()) {
      return Measurement<double>();
    }
    std::vector<double> densities;
    densities.reserve(this->graph().nEdges());
    if constexpr (Normalized) {
      for (const auto& [streetId, pStreet] : this->graph().edges()) {
        densities.push_back(pStreet->density<true>());
      }
    } else {
      double sum{0.};
      for (const auto& [streetId, pStreet] : this->graph().edges()) {
        densities.push_back(pStreet->density<false>() * pStreet->length());
        sum += pStreet->length();
      }
      if (sum == 0) {
        return Measurement<double>();
      }
      auto meanDensity{std::accumulate(densities.begin(), densities.end(), 0.) / sum};
      return Measurement<double>(meanDensity, 0., densities.size());
    }
    return Measurement<double>(densities);
  }

}  // namespace dsf::mobility
