name: "CI: Pytest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential doxygen libtbb-dev
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pandas polars
    
    - name: Install package
      run: |
        pip install -e .
    
    - name: Run tests with pytest
      run: |
        pytest test -v --cov=src/dsf --cov-report=term-missing -o "python_files=Test_*.py test_*.py Bind_*.py"
